/**
 * @file version.h
 * @brief Sim stand-in for the firmware's generated version.h.
 *
 * On target this header is regenerated by the build next to autoconf.h and
 * carries three U32s describing the firmware image. The sim pins them to fixed
 * values instead of regenerating: a build timestamp that moved on every run
 * would rewrite the boot record on every run, recompiling n_ww_log_control.c
 * and churning the archive for no reason.
 *
 * Only BUILD_VERSION and BUILD_GIT_ID reach the log stream (see the boot record
 * in n_ww_log_def.h); BUILD_TIME is here to mirror the real header.
 */

#ifndef __VERSION_H__
#define __VERSION_H__

#define BUILD_TIME      0x20260819u
#define BUILD_VERSION   0x00020000u   /* v2.0.0 */
#define BUILD_GIT_ID    0x5A1D0000u

#endif /* __VERSION_H__ */
