#!/usr/bin/env python3
"""
File ID Generator for WW Log System
Generates Makefile variable definitions and C header from log_config.json

All module configuration is centralized in log_config.json:
- Module IDs and names
- Module enable/disable (static compile-time switch)
- File IDs and mappings
"""

import json
import sys
import os
from pathlib import Path

def load_config(config_file):
    """Load configuration from JSON file"""
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Configuration file '{config_file}' not found", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in '{config_file}': {e}", file=sys.stderr)
        sys.exit(1)

def generate_makefile_vars(config):
    """Generate Makefile variable definitions"""
    modules = config.get('modules', {})
    files = config.get('files', {})

    lines = []
    lines.append("# Auto-generated file ID mappings")
    lines.append("# Generated by tools/gen_file_ids.py")
    lines.append("# DO NOT EDIT MANUALLY")
    lines.append("")

    # Statistics
    enabled_count = 0
    disabled_count = 0

    for file_path, file_info in sorted(files.items()):
        module_name = file_info.get('module')
        if not module_name:
            print(f"Warning: No module specified for {file_path}", file=sys.stderr)
            continue

        module = modules.get(module_name)
        if not module:
            print(f"Warning: Module '{module_name}' not found for {file_path}", file=sys.stderr)
            continue

        module_enabled = module.get('enable', True)

        if not module_enabled:
            # Module disabled, don't generate ID
            lines.append(f"# {file_path}: Module {module_name} DISABLED")
            disabled_count += 1
            continue

        # Calculate final ID: base_id + offset
        base_id = module.get('base_id', 0)
        offset = file_info.get('offset', 0)
        file_id = base_id + offset
        module_id = module.get('id', 0)

        # Generate Makefile variable (replace special characters)
        # Convert path to valid Make variable name
        var_name = f"FILE_ID_{file_path}".replace('/', '_').replace('.', '_').replace('-', '_')
        module_var_name = f"MODULE_ID_{file_path}".replace('/', '_').replace('.', '_').replace('-', '_')
        static_var_name = f"MODULE_STATIC_EN_{file_path}".replace('/', '_').replace('.', '_').replace('-', '_')

        # Add comment with description if available
        desc = file_info.get('description', '')
        if desc:
            lines.append(f"# {file_path}: {desc} (Module: {module_name}, ID: {module_id})")

        lines.append(f"{var_name} = {file_id}")
        lines.append(f"{module_var_name} = {module_id}")
        lines.append(f"{static_var_name} = 1")  # Module is enabled
        enabled_count += 1

    lines.append("")
    lines.append(f"# Summary: {enabled_count} files enabled, {disabled_count} files disabled")

    return '\n'.join(lines)

def generate_c_header(config):
    """Generate C header file with module definitions and file IDs"""
    modules = config.get('modules', {})
    files = config.get('files', {})

    lines = []
    lines.append("/**")
    lines.append(" * @file auto_file_ids.h")
    lines.append(" * @brief Auto-generated module and file ID definitions")
    lines.append(" * @note DO NOT EDIT MANUALLY - Generated by tools/gen_file_ids.py from log_config.json")
    lines.append(" *")
    lines.append(" * This file contains:")
    lines.append(" * - Module ID definitions (WW_LOG_MODULE_XXX)")
    lines.append(" * - File ID definitions (FILE_ID_XXX)")
    lines.append(" *")
    lines.append(" * Note: Module enable/disable is controlled by Makefile via CURRENT_MODULE_STATIC_EN")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef AUTO_FILE_IDS_H")
    lines.append("#define AUTO_FILE_IDS_H")
    lines.append("")

    # ========== Module ID Definitions ==========
    lines.append("/* ========== Module ID Definitions ========== */")
    lines.append("")

    # Sort modules by ID
    sorted_modules = sorted(modules.items(), key=lambda x: x[1].get('id', 0))

    for module_name, module_info in sorted_modules:
        module_id = module_info.get('id', 0)
        desc = module_info.get('description', '')
        if desc:
            lines.append(f"#define WW_LOG_MODULE_{module_name.upper()}  {module_id}  /**< {desc} */")
        else:
            lines.append(f"#define WW_LOG_MODULE_{module_name.upper()}  {module_id}")

    lines.append("")
    lines.append(f"#define WW_LOG_MODULE_MAX  32  /**< Maximum number of modules */")
    lines.append("")

    # ========== File ID Definitions ==========
    lines.append("/* ========== File ID Definitions ========== */")
    lines.append("")

    # Group by module
    for module_name, module_info in sorted_modules:
        if not module_info.get('enable', True):
            lines.append(f"/* {module_name} Module - DISABLED */")
            lines.append("")
            continue

        lines.append(f"/* {module_name} Module (ID: {module_info.get('id', 0)}, Base: {module_info.get('base_id', 0)}) */")

        # Find files in this module
        module_files = [(path, info) for path, info in files.items()
                       if info.get('module') == module_name]

        for file_path, file_info in sorted(module_files):
            base_id = module_info.get('base_id', 0)
            offset = file_info.get('offset', 0)
            file_id = base_id + offset

            # Create safe C macro name
            safe_name = file_path.replace('/', '_').replace('.', '_').replace('-', '_').upper()
            desc = file_info.get('description', '')

            if desc:
                lines.append(f"#define FILE_ID_{safe_name}  {file_id}  /* {desc} */")
            else:
                lines.append(f"#define FILE_ID_{safe_name}  {file_id}")

        lines.append("")

    lines.append("#endif /* AUTO_FILE_IDS_H */")

    return '\n'.join(lines)

def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: gen_file_ids.py <config.json> [--makefile|--header]")
        print("")
        print("Options:")
        print("  --makefile  Generate Makefile variable definitions (default)")
        print("  --header    Generate C header file with module and file IDs")
        sys.exit(1)

    config_file = sys.argv[1]
    output_type = sys.argv[2] if len(sys.argv) > 2 else '--makefile'

    # Load configuration
    config = load_config(config_file)

    # Generate output based on type
    if output_type == '--makefile':
        output = generate_makefile_vars(config)
    elif output_type == '--header':
        output = generate_c_header(config)
    else:
        print(f"Error: Unknown output type '{output_type}'", file=sys.stderr)
        print("Use --makefile or --header", file=sys.stderr)
        sys.exit(1)

    # Print to stdout
    print(output)

if __name__ == '__main__':
    main()
