#ifndef FILE_IDS_H
#define FILE_IDS_H

typedef enum {
    FILE_ID_INCLUDE_FILE_IDS_H = 0,
    FILE_ID_INCLUDE_LOG_API_H = 1,
    FILE_ID_INCLUDE_LOG_CONFIG_H = 2,
    FILE_ID_INCLUDE_LOG_FILTER_H = 3,
    FILE_ID_INCLUDE_LOG_STORAGE_H = 4,
    FILE_ID_INCLUDE_LOG_TYPES_H = 5,
    FILE_ID_MODULES_APP_MAIN_APP_C = 256,
    FILE_ID_MODULES_DRIVER_UART_DRIVER_C = 512,
    FILE_ID_SRC_FILE_IDS_C = 768,
    FILE_ID_SRC_LOG_ENCODE_C = 769,
    FILE_ID_SRC_LOG_FILTER_C = 770,
    FILE_ID_SRC_LOG_STORAGE_C = 771,
    FILE_ID_SRC_LOG_STR_C = 772,
    FILE_ID_TEST_LOG_TEST_C = 1024,
    FILE_ID_MAX
} file_id_t;

extern const char* file_names[FILE_ID_MAX];

#endif
