/**
 * @file auto_file_ids.h
 * @brief Auto-generated module and file ID definitions
 * @note DO NOT EDIT MANUALLY - Generated by tools/gen_file_ids.py from log_config.json
 *
 * This file contains:
 * - Module ID definitions (WW_LOG_MODULE_XXX)
 * - File ID definitions (FILE_ID_XXX)
 *
 * Note: Module enable/disable is controlled by Makefile via CURRENT_MODULE_STATIC_EN
 */

#ifndef AUTO_FILE_IDS_H
#define AUTO_FILE_IDS_H

/* ========== Module ID Definitions ========== */

#define WW_LOG_MODULE_DEFAULT  0  /**< Default/System module */
#define WW_LOG_MODULE_DEMO  1  /**< Demo module */
#define WW_LOG_MODULE_TEST  2  /**< Test module */
#define WW_LOG_MODULE_APP  3  /**< Application module */
#define WW_LOG_MODULE_DRIVERS  4  /**< Drivers module */
#define WW_LOG_MODULE_BROM  5  /**< BROM module */

#define WW_LOG_MODULE_MAX  32  /**< Maximum number of modules */

/* ========== File ID Definitions ========== */

/* DEFAULT Module - DISABLED */

/* DEMO Module (ID: 1, Base: 64) */
#define FILE_ID_SRC_DEMO_DEMO_INIT_C  64  /* Demo initialization */
#define FILE_ID_SRC_DEMO_DEMO_PROCESS_C  65  /* Demo process */

/* TEST Module (ID: 2, Base: 128) */
#define FILE_ID_SRC_TEST_TEST_DEFAULT_VALUE_C  134  /* Default value test */
#define FILE_ID_SRC_TEST_TEST_FILE_ID_SCENARIOS_C  132  /* File ID scenarios */
#define FILE_ID_SRC_TEST_TEST_INTEGRATION_C  130  /* Integration tests */
#define FILE_ID_SRC_TEST_TEST_NO_FILE_ID_C  133  /* No file ID test */
#define FILE_ID_SRC_TEST_TEST_STRESS_C  131  /* Stress tests */
#define FILE_ID_SRC_TEST_TEST_UNIT_C  129  /* Unit tests */

/* APP Module - DISABLED */

/* DRIVERS Module (ID: 4, Base: 256) */
#define FILE_ID_SRC_DRIVERS_DRV_I2C_C  259  /* I2C driver */
#define FILE_ID_SRC_DRIVERS_DRV_SPI_C  258  /* SPI driver */
#define FILE_ID_SRC_DRIVERS_DRV_UART_C  257  /* UART driver */

/* BROM Module - DISABLED */

#endif /* AUTO_FILE_IDS_H */
