/**
 * @file log_file_id.h
 * @brief Auto-generated file ID definitions for logging system
 * 
 * ⚠️  WARNING: DO NOT EDIT MANUALLY
 * This file is automatically generated by tools/generate_file_ids.py
 * 
 * Generated at: 2025-11-24 07:07:36
 * Total files: 12
 */

#ifndef LOG_FILE_ID_H
#define LOG_FILE_ID_H

typedef enum {
    /* BROM Module - BROM initialization and startup code (1-50) */
    FILE_ID_BROM_BROM_BOOT = 1,  /* src/brom/brom_boot.c */
    FILE_ID_BROM_BROM_LOADER = 2,  /* src/brom/brom_loader.c */

    /* DRIVERS Module - Hardware drivers (UART, SPI, I2C, etc.) (51-150) */
    FILE_ID_DRIVERS_DRV_I2C = 51,  /* src/drivers/drv_i2c.c */
    FILE_ID_DRIVERS_DRV_SPI = 52,  /* src/drivers/drv_spi.c */
    FILE_ID_DRIVERS_DRV_UART = 53,  /* src/drivers/drv_uart.c */

    /* APP Module - Application logic and business code (151-250) */
    FILE_ID_APP_APP_CONFIG = 151,  /* src/app/app_config.c */
    FILE_ID_APP_APP_MAIN = 152,  /* src/app/app_main.c */

    /* TEST Module - Unit tests and integration tests (251-300) */
    FILE_ID_TEST_TEST_INTEGRATION = 251,  /* src/test/test_integration.c */
    FILE_ID_TEST_TEST_STRESS = 252,  /* src/test/test_stress.c */
    FILE_ID_TEST_TEST_UNIT = 253,  /* src/test/test_unit.c */

    /* DEMO Module - Demo applications and examples (301-350) */
    FILE_ID_DEMO_DEMO_INIT = 301,  /* src/demo/demo_init.c */
    FILE_ID_DEMO_DEMO_PROCESS = 302,  /* src/demo/demo_process.c */

} LOG_FILE_ID_E;

#endif /* LOG_FILE_ID_H */